### ISSUE TITLE
Doesn't work on mobile

### ISSUE THREAD

**Issue by im-izz** [roteKlaue/firefox-startpage-search-extension#1]
Is it made for mobile? since I can't find the Startpage extension on mobile and only found this one

**Comment by roteKlaue** [comment]
Hello,
No it does not. I marked it on accident and i don't know how to unmark it.
But you can add one in the settings.
1. Open Settings
![Screenshot_20240902-121854_Firefox](https://github.com/user-attachments/assets/c0e26053-5b3d-46e6-9f03-c0792fab5353)
2. Open Search Settings
![Screenshot_20240902-121925_Firefox](https://github.com/user-attachments/assets/55dd782a-6936-4310-9eb7-01b98e13ada9)
3. Open Default Search Engine
![Screenshot_20240902-121931_Firefox](https://github.com/user-attachments/assets/4b1c9b7e-840c-4c6d-ab25-f81f243f2a37)
4. Add new Search Engine
![Untitled design](https://github.com/user-attachments/assets/ef0f8723-36da-4f3a-b4eb-a04b23f8a567)
